services:
  # Your API – builds from Dockerfile
  - type: web
    name: graphrag-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeployTrigger: commit
    healthCheckPath: /healthz
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LITELLM_MODEL
        value: openai/gpt-4.1
      - key: FALKOR_HOST
        fromService:
          name: falkordb
          type: pserv
          property: host
      - key: FALKOR_PORT
        fromService:
          name: falkordb
          type: pserv
          property: port
    dependsOn:
      - falkordb

  # FalkorDB – runs as a private service, pulled from Docker Hub
  - type: pserv
    name: falkordb
    runtime: image
    image:
      url: falkordb/falkordb:latest
    plan: starter
    disk:
      name: falkor-data
      mountPath: /data
      sizeGB: 5
